# Generated by Django 4.1.3 on 2022-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('searching', 'Поиск'), ('closed', 'Закрыто'), ('waiting_response', 'Ожидание ответа')], max_length=255, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=255, verbose_name='Приоритет')),
                ('hr_manager', models.CharField(max_length=255, verbose_name='Ответственный HR')),
                ('file', models.FileField(upload_to='vacancys_files/$Y/%m/$d/', verbose_name='Файл')),
                ('time_creat', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
