# Generated by Django 4.1.3 on 2022-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('estimation', models.IntegerField(verbose_name='Оценка')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=255, verbose_name='номер телефона')),
                ('status', models.CharField(choices=[('in_progress', 'В обработке'), ('wait_response', 'Ожидание ответа'), ('sened_offer', 'Оффер отправлен'), ('need_call', 'Требуется звонок'), ('rejection', 'Отказ'), ('closed', 'Вакансия закрыта'), ('test_task', 'Тест отправлен')], max_length=255, verbose_name='Статус')),
                ('hr_manager', models.CharField(max_length=255, verbose_name='Ответсвенный HR')),
                ('file', models.FileField(upload_to='candidates_files/$Y/%m/$d/', verbose_name='Файл резюме')),
                ('time_creat', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
