# Generated by Django 4.1.3 on 2022-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0002_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['time_creat', 'time_update'], 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['time_creat', 'time_update'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vacancys_files/$Y/%m/$d/', verbose_name='Файл'),
        ),
    ]
