# Generated by Django 4.1.3 on 2022-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0003_alter_candidate_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='in_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
