# Generated by Django 4.1.3 on 2022-12-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0004_candidate_in_archive_vacancy_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='file',
        ),
    ]
